name: OpenAPIClient
targets:
  OpenAPIClient:
    type: framework
    platform: iOS
    deploymentTarget: "11.0"
    sources: [OpenAPIClient]
    info:
      path: ./Info.plist
      version: 2024-04-20 19:46:57UTC
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
