//
// CurrentPosition.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CurrentPosition: Codable, JSONEncodable, Hashable {

    public var id: String
    public var name: String
    public var xCoord: String
    public var yCoord: String

    public init(id: String, name: String, xCoord: String, yCoord: String) {
        self.id = id
        self.name = name
        self.xCoord = xCoord
        self.yCoord = yCoord
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case xCoord
        case yCoord
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(xCoord, forKey: .xCoord)
        try container.encode(yCoord, forKey: .yCoord)
    }
}

