//
// FriendRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FriendRequest: Codable, JSONEncodable, Hashable {

    public var id: String
    public var senderEmail: String
    public var sender: Friend
    public var recipient: String

    public init(id: String, senderEmail: String, sender: Friend, recipient: String) {
        self.id = id
        self.senderEmail = senderEmail
        self.sender = sender
        self.recipient = recipient
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case senderEmail
        case sender
        case recipient
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(senderEmail, forKey: .senderEmail)
        try container.encode(sender, forKey: .sender)
        try container.encode(recipient, forKey: .recipient)
    }
}

