//
// Friend.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Friend: Codable, JSONEncodable, Hashable {

    public var id: String
    public var name: String
    public var isTracking: Bool

    public init(id: String, name: String, isTracking: Bool) {
        self.id = id
        self.name = name
        self.isTracking = isTracking
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case isTracking
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(isTracking, forKey: .isTracking)
    }
}

