//
// LeaderBoard.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LeaderBoard: Codable, JSONEncodable, Hashable {

    public var id: String
    public var name: String
    public var distance: Double
    public var totalTimeInSeconds: Double

    public init(id: String, name: String, distance: Double, totalTimeInSeconds: Double) {
        self.id = id
        self.name = name
        self.distance = distance
        self.totalTimeInSeconds = totalTimeInSeconds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case distance
        case totalTimeInSeconds
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(distance, forKey: .distance)
        try container.encode(totalTimeInSeconds, forKey: .totalTimeInSeconds)
    }
}

