//
// TrackedPath.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TrackedPath: Codable, JSONEncodable, Hashable {

    public var id: String
    public var name: String
    public var startDate: String
    public var endDate: String
    public var notes: [String]?
    public var xCoords: [Double]?
    public var yCoords: [Double]?
    public var tracking: Bool

    public init(id: String, name: String, startDate: String, endDate: String, notes: [String]? = nil, xCoords: [Double]? = nil, yCoords: [Double]? = nil, tracking: Bool) {
        self.id = id
        self.name = name
        self.startDate = startDate
        self.endDate = endDate
        self.notes = notes
        self.xCoords = xCoords
        self.yCoords = yCoords
        self.tracking = tracking
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case startDate
        case endDate
        case notes
        case xCoords
        case yCoords
        case tracking
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(startDate, forKey: .startDate)
        try container.encode(endDate, forKey: .endDate)
        try container.encodeIfPresent(notes, forKey: .notes)
        try container.encodeIfPresent(xCoords, forKey: .xCoords)
        try container.encodeIfPresent(yCoords, forKey: .yCoords)
        try container.encode(tracking, forKey: .tracking)
    }
}

