//
// UserFriendDeletion.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserFriendDeletion: Codable, JSONEncodable, Hashable {

    public var userId: String
    public var friendId: String

    public init(userId: String, friendId: String) {
        self.userId = userId
        self.friendId = friendId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userId
        case friendId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(userId, forKey: .userId)
        try container.encode(friendId, forKey: .friendId)
    }
}

