//
// UserTrackedPaths.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserTrackedPaths: Codable, JSONEncodable, Hashable {

    public var id: String
    public var tracks: [TrackedPath]?
    public var sharedTracks: [TrackedPath]?

    public init(id: String, tracks: [TrackedPath]? = nil, sharedTracks: [TrackedPath]? = nil) {
        self.id = id
        self.tracks = tracks
        self.sharedTracks = sharedTracks
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case tracks
        case sharedTracks
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(tracks, forKey: .tracks)
        try container.encodeIfPresent(sharedTracks, forKey: .sharedTracks)
    }
}

