//
// UserfriendList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserfriendList: Codable, JSONEncodable, Hashable {

    public var id: String
    public var friends: [Friend]?

    public init(id: String, friends: [Friend]? = nil) {
        self.id = id
        self.friends = friends
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case friends
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(friends, forKey: .friends)
    }
}

